# Generated by Django 2.0.1 on 2018-11-04 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bunrui',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bunrui', models.CharField(max_length=50, verbose_name='分類')),
            ],
        ),
        migrations.CreateModel(
            name='Bushu',
            fields=[
                ('bushu', models.CharField(max_length=1, primary_key=True, serialize=False, verbose_name='BUSHU')),
                ('reading', models.CharField(max_length=3, verbose_name='READING')),
            ],
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(max_length=6, verbose_name='種別')),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_kind', models.CharField(choices=[('KAKI', '書き取り'), ('YOMI', '読み'), ('HYOGAI', '表外読み'), ('TAIGI', '対義語'), ('RUIGI', '類義語'), ('KOTOWAZA', '故事・諺')], default='KAKI', max_length=8, verbose_name='種類')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='作成日付')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='変更日付')),
                ('word', models.CharField(max_length=20, verbose_name='単語')),
                ('word_native', models.CharField(blank=True, max_length=10, verbose_name='単語（例文）')),
                ('yomi', models.CharField(blank=True, max_length=30, verbose_name='読み方')),
                ('yomi_native', models.CharField(blank=True, max_length=30, verbose_name='読み方（例文）')),
                ('word_variation', models.CharField(blank=True, max_length=20, verbose_name='他の書き方')),
                ('sentence', models.CharField(blank=True, max_length=300, verbose_name='例文')),
                ('definition', models.CharField(blank=True, max_length=10000, verbose_name='意味')),
                ('is_joyo', models.BooleanField(verbose_name='常表例')),
            ],
        ),
        migrations.CreateModel(
            name='ExMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ateji', models.BooleanField()),
                ('in_joyo_list', models.BooleanField()),
                ('map_order', models.IntegerField()),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kukan.Example')),
            ],
            options={
                'ordering': ['map_order'],
            },
        ),
        migrations.CreateModel(
            name='JisClass',
            fields=[
                ('level', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='JIS水準')),
            ],
        ),
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('kanji', models.CharField(max_length=1, primary_key=True, serialize=False, verbose_name='漢字')),
                ('strokes', models.IntegerField(verbose_name='画数')),
                ('bushu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kukan.Bushu', verbose_name='部首')),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kukan.Classification', verbose_name='種別')),
                ('jis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kukan.JisClass', verbose_name='JIS水準')),
            ],
        ),
        migrations.CreateModel(
            name='KanjiDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.TextField(blank=True, max_length=1000, verbose_name='意味')),
                ('external_ref', models.CharField(blank=True, max_length=1000, verbose_name='外部辞典')),
                ('anki_English', models.CharField(blank=True, max_length=1000)),
                ('anki_Examples', models.CharField(blank=True, max_length=1000)),
                ('anki_Kanji_Radical', models.CharField(blank=True, max_length=10)),
                ('anki_Traditional_Form', models.CharField(blank=True, max_length=10)),
                ('anki_Traditional_Radical', models.CharField(blank=True, max_length=10)),
                ('anki_Reading_Table', models.CharField(blank=True, max_length=10000)),
                ('anki_kjBushuMei', models.CharField(blank=True, max_length=100)),
                ('anki_kjIjiDoukun', models.CharField(blank=True, max_length=5000)),
                ('kanji', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kukan.Kanji', verbose_name='漢字')),
                ('std_kanji', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kyoyojitai', to='kukan.Kanji')),
            ],
        ),
        migrations.CreateModel(
            name='Kanken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kyu', models.CharField(max_length=3, verbose_name='漢字検定')),
                ('difficulty', models.IntegerField()),
                ('item_01_name', models.CharField(blank=True, max_length=20)),
                ('item_01', models.IntegerField(default=0, verbose_name='一')),
                ('item_02_name', models.CharField(blank=True, max_length=20)),
                ('item_02', models.IntegerField(default=0, verbose_name='二')),
                ('item_03_name', models.CharField(blank=True, max_length=20)),
                ('item_03', models.IntegerField(default=0, verbose_name='三')),
                ('item_04_name', models.CharField(blank=True, max_length=20)),
                ('item_04', models.IntegerField(default=0, verbose_name='四')),
                ('item_05_name', models.CharField(blank=True, max_length=20)),
                ('item_05', models.IntegerField(default=0, verbose_name='五')),
                ('item_06_name', models.CharField(blank=True, max_length=20)),
                ('item_06', models.IntegerField(default=0, verbose_name='六')),
                ('item_07_name', models.CharField(blank=True, max_length=20)),
                ('item_07', models.IntegerField(default=0, verbose_name='七')),
                ('item_08_name', models.CharField(blank=True, max_length=20)),
                ('item_08', models.IntegerField(default=0, verbose_name='八')),
                ('item_09_name', models.CharField(blank=True, max_length=20)),
                ('item_09', models.IntegerField(default=0, verbose_name='九')),
                ('item_10_name', models.CharField(blank=True, max_length=20)),
                ('item_10', models.IntegerField(default=0, verbose_name='十')),
                ('success_line', models.IntegerField(default=0, verbose_name='合格基準')),
            ],
            options={
                'ordering': ['difficulty'],
            },
        ),
        migrations.CreateModel(
            name='Kotowaza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kotowaza', models.CharField(max_length=100, verbose_name='諺')),
                ('yomi', models.CharField(blank=True, max_length=100, verbose_name='読み方')),
                ('furigana', models.CharField(blank=True, max_length=200, verbose_name='振り仮名')),
                ('definition', models.CharField(blank=True, max_length=10000, verbose_name='諺の意味')),
            ],
        ),
        migrations.CreateModel(
            name='KoukiBushu',
            fields=[
                ('bushu', models.CharField(max_length=1, primary_key=True, serialize=False, verbose_name='BUSHU')),
                ('variations', models.CharField(max_length=5, verbose_name='VARIATIONS')),
                ('reading', models.CharField(max_length=50, verbose_name='READING')),
                ('number', models.IntegerField()),
                ('kakusu', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading', models.CharField(max_length=20, verbose_name='読み')),
                ('reading_simple', models.CharField(max_length=20, verbose_name='読み')),
                ('joyo_order', models.IntegerField(blank=True, verbose_name='常用漢字表・順番')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='備考')),
                ('ijidokun', models.CharField(blank=True, max_length=200, verbose_name='異字同訓')),
            ],
            options={
                'ordering': ['yomi_type', 'joyo_order'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('test_source', models.CharField(choices=[('TEST', '試験'), ('3K1', '漢字検定試験問題集３級－平成２９年版'), ('J2K1', '漢字検定試験問題集準２級－平成２９年版'), ('2K1', '漢字検定試験問題集２級－平成３０年版'), ('2K2', '漢字検定インターネット問題例'), ('2K3', '漢検過去問題集２級－平成３０年度版')], max_length=4, verbose_name='問題集')),
                ('test_number', models.IntegerField(default=0, verbose_name='問題番号')),
                ('name', models.CharField(choices=[('OGU', '大具'), ('COGU', '小具')], max_length=4, verbose_name='名前')),
                ('item_01', models.IntegerField(default=0, verbose_name='一')),
                ('item_02', models.IntegerField(default=0, verbose_name='二')),
                ('item_03', models.IntegerField(default=0, verbose_name='三')),
                ('item_04', models.IntegerField(default=0, verbose_name='四')),
                ('item_05', models.IntegerField(default=0, verbose_name='五')),
                ('item_06', models.IntegerField(default=0, verbose_name='六')),
                ('item_07', models.IntegerField(default=0, verbose_name='七')),
                ('item_08', models.IntegerField(default=0, verbose_name='八')),
                ('item_09', models.IntegerField(default=0, verbose_name='九')),
                ('item_10', models.IntegerField(default=0, verbose_name='十')),
                ('score', models.IntegerField(default=0, editable=False, verbose_name='総合得点')),
                ('kanken', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kukan.Kanken', verbose_name='漢検')),
            ],
        ),
        migrations.CreateModel(
            name='Yoji',
            fields=[
                ('yoji', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='四字熟語')),
                ('reading', models.CharField(max_length=100, verbose_name='読み方')),
                ('meaning', models.TextField(blank=True, max_length=10000, verbose_name='意味')),
                ('has_jitenon_kyu', models.BooleanField(default=False, verbose_name='級記有無')),
                ('external_ref', models.CharField(blank=True, max_length=1000, verbose_name='外部辞典')),
                ('in_anki', models.BooleanField(default=False, verbose_name='日課')),
                ('anki_cloze', models.CharField(blank=True, max_length=4, verbose_name='Cloze sequence')),
                ('bunrui', models.ManyToManyField(blank=True, to='kukan.Bunrui')),
                ('kanken', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kukan.Kanken', verbose_name='漢検')),
            ],
        ),
        migrations.CreateModel(
            name='YomiJoyo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yomi_joyo', models.CharField(max_length=5, verbose_name='常用漢字表')),
            ],
        ),
        migrations.CreateModel(
            name='YomiType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yomi_type', models.CharField(max_length=1, verbose_name='読み種別')),
            ],
        ),
        migrations.AddField(
            model_name='reading',
            name='joyo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kukan.YomiJoyo', verbose_name='常用漢字表'),
        ),
        migrations.AddField(
            model_name='reading',
            name='kanji',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kukan.Kanji', verbose_name='漢字'),
        ),
        migrations.AddField(
            model_name='reading',
            name='yomi_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kukan.YomiType', verbose_name='音訓'),
        ),
        migrations.AddField(
            model_name='kanji',
            name='kanken',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kukan.Kanken', verbose_name='漢検'),
        ),
        migrations.AddField(
            model_name='kanji',
            name='kouki_bushu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kukan.KoukiBushu', verbose_name='康煕部首'),
        ),
        migrations.AddField(
            model_name='exmap',
            name='kanji',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kukan.Kanji'),
        ),
        migrations.AddField(
            model_name='exmap',
            name='reading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kukan.Reading'),
        ),
        migrations.AddField(
            model_name='example',
            name='kanjis',
            field=models.ManyToManyField(through='kukan.ExMap', to='kukan.Kanji'),
        ),
        migrations.AddField(
            model_name='example',
            name='kanken',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kukan.Kanken', verbose_name='漢検'),
        ),
        migrations.AddField(
            model_name='example',
            name='kotowaza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kukan.Kotowaza', verbose_name='諺'),
        ),
        migrations.AddField(
            model_name='example',
            name='readings',
            field=models.ManyToManyField(to='kukan.Reading'),
        ),
        migrations.AlterUniqueTogether(
            name='reading',
            unique_together={('kanji', 'reading')},
        ),
        migrations.AddIndex(
            model_name='example',
            index=models.Index(fields=['word', 'yomi'], name='kukan_examp_word_5cc14c_idx'),
        ),
        migrations.AddIndex(
            model_name='example',
            index=models.Index(fields=['word'], name='kukan_examp_word_d69ec8_idx'),
        ),
    ]
