# Generated by Django 2.0.1 on 2018-02-18 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bushu',
            fields=[
                ('bushu', models.CharField(max_length=1, primary_key=True, serialize=False, verbose_name='BUSHU')),
                ('reading', models.CharField(max_length=3, verbose_name='READING')),
            ],
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(max_length=6, verbose_name='種別')),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=5, verbose_name='例')),
                ('yomi', models.CharField(blank=True, max_length=30, verbose_name='読み方')),
                ('sentence', models.CharField(blank=True, max_length=300, verbose_name='文章')),
                ('definition', models.CharField(blank=True, max_length=2000, verbose_name='定義')),
                ('is_joyo', models.BooleanField(verbose_name='常用漢字表の例')),
            ],
        ),
        migrations.CreateModel(
            name='ExMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_joyo_list', models.BooleanField()),
                ('map_order', models.IntegerField()),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kukan.Example')),
            ],
            options={
                'ordering': ['map_order'],
            },
        ),
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('kanji', models.CharField(max_length=1, primary_key=True, serialize=False, verbose_name='漢字')),
                ('kanken_kyu', models.CharField(max_length=3, verbose_name='漢字検定')),
                ('strokes', models.IntegerField(verbose_name='画数')),
                ('jukuji', models.CharField(blank=True, max_length=200, verbose_name='熟字・当て字')),
                ('anki_Kanji', models.CharField(max_length=10)),
                ('anki_Onyomi', models.CharField(max_length=100)),
                ('anki_Kunyomi', models.CharField(max_length=100)),
                ('anki_Nanori', models.CharField(max_length=100)),
                ('anki_English', models.CharField(max_length=1000)),
                ('anki_Examples', models.CharField(max_length=1000)),
                ('anki_JLPT_Level', models.CharField(max_length=10)),
                ('anki_Jouyou_Grade', models.CharField(max_length=10)),
                ('anki_Frequency', models.CharField(max_length=10)),
                ('anki_Components', models.CharField(max_length=1000)),
                ('anki_Number_of_Strokes', models.CharField(max_length=10)),
                ('anki_Kanji_Radical', models.CharField(max_length=10)),
                ('anki_Radical_Number', models.CharField(max_length=10)),
                ('anki_Radical_Strokes', models.CharField(max_length=10)),
                ('anki_Radical_Reading', models.CharField(max_length=10)),
                ('anki_Traditional_Form', models.CharField(max_length=10)),
                ('anki_Classification', models.CharField(max_length=10)),
                ('anki_Keyword', models.CharField(max_length=100)),
                ('anki_Traditional_Radical', models.CharField(max_length=10)),
                ('anki_Reading_Table', models.CharField(max_length=10000)),
                ('anki_kjBushu', models.CharField(max_length=10)),
                ('anki_kjBushuMei', models.CharField(max_length=100)),
                ('anki_kjKanjiKentei', models.CharField(max_length=10)),
                ('anki_kjBunrui', models.CharField(max_length=10)),
                ('anki_kjIjiDoukun', models.CharField(max_length=5000)),
                ('bushu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kukan.Bushu', verbose_name='部首')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kukan.Classification', verbose_name='種別')),
            ],
            options={
                'ordering': ['kanji'],
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading', models.CharField(max_length=20, verbose_name='読み')),
                ('joyo_order', models.IntegerField(blank=True, verbose_name='常用漢字表・順番')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='備考')),
                ('ijidokun', models.CharField(blank=True, max_length=200, verbose_name='異字同訓')),
            ],
            options={
                'ordering': ['yomi_type', 'joyo_order'],
            },
        ),
        migrations.CreateModel(
            name='YomiJoyo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yomi_joyo', models.CharField(max_length=5, verbose_name='常用漢字表')),
            ],
        ),
        migrations.CreateModel(
            name='YomiType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yomi_type', models.CharField(max_length=1, verbose_name='読み種別')),
            ],
        ),
        migrations.AddField(
            model_name='reading',
            name='joyo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kukan.YomiJoyo', verbose_name='常用漢字表'),
        ),
        migrations.AddField(
            model_name='reading',
            name='kanji',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kukan.Kanji', verbose_name='漢字'),
        ),
        migrations.AddField(
            model_name='reading',
            name='yomi_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kukan.YomiType', verbose_name='音訓'),
        ),
        migrations.AddField(
            model_name='exmap',
            name='kanji',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kukan.Kanji'),
        ),
        migrations.AddField(
            model_name='exmap',
            name='reading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kukan.Reading'),
        ),
        migrations.AddField(
            model_name='example',
            name='kanjis',
            field=models.ManyToManyField(through='kukan.ExMap', to='kukan.Kanji'),
        ),
        migrations.AddField(
            model_name='example',
            name='readings',
            field=models.ManyToManyField(to='kukan.Reading'),
        ),
        migrations.AlterUniqueTogether(
            name='reading',
            unique_together={('kanji', 'reading')},
        ),
        migrations.AddIndex(
            model_name='example',
            index=models.Index(fields=['word', 'yomi'], name='kukan_examp_word_5cc14c_idx'),
        ),
        migrations.AddIndex(
            model_name='example',
            index=models.Index(fields=['word'], name='kukan_examp_word_d69ec8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='example',
            unique_together={('word', 'yomi')},
        ),
    ]
