# Generated by Django 2.0.1 on 2018-02-25 22:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kukan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanji',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 31, 0, 0), verbose_name='変更日付'),
            preserve_default=False,
        ),
    ]
