# Generated by Django 2.1.5 on 2020-04-05 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kukan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=50, verbose_name='問題集')),
                ('kyu', models.CharField(max_length=20, verbose_name='級')),
                ('year', models.CharField(max_length=20, verbose_name='年度')),
                ('section', models.CharField(blank=True, default='', max_length=20, verbose_name='区分')),
            ],
        ),
        migrations.AddField(
            model_name='example',
            name='definition2',
            field=models.CharField(blank=True, max_length=10000, verbose_name='意味（乙）'),
        ),
        migrations.AlterField(
            model_name='example',
            name='ex_kind',
            field=models.CharField(choices=[('KAKI', '書き取り'), ('YOMI', '読み'), ('HYOGAI', '表外読み'), ('TAIGI', '対義語'), ('RUIGI', '類義語'), ('KOTOWAZA', '故事・諺'), ('JUKUICHI', '熟語と一字訓')], default='KAKI', max_length=8, verbose_name='種類'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='test_source',
            field=models.CharField(choices=[('TEST', '試験'), ('3K1', '漢字検定試験問題集３級－平成２９年版'), ('J2K1', '漢字検定試験問題集準２級－平成２９年版'), ('2K1', '漢字検定試験問題集２級－平成３０年版'), ('2K2', '漢字検定インターネット問題例'), ('2K3', '漢検２級\u3000過去問題集－平成３０年度版'), ('J1K1', '漢字検定試験問題集準１級－2019年度版'), ('1KJ1K1', '漢検１／準１級\u3000過去問題集－2019年度版'), ('1KJ1K2', '漢検１／準１級\u3000過去問題集－平成３０年度版'), ('1KJ1K2', '漢検１／準１級\u3000過去問題集－平成２９年度版'), ('1KJ1K3', '漢検１／準１級\u3000過去問題集－平成２８年度版')], max_length=8, verbose_name='問題集'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='kukan.TestSource', verbose_name='問題元'),
        ),
    ]
