# Generated by Django 2.0.1 on 2018-02-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kukan', '0002_kanji_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='definition',
            field=models.CharField(blank=True, max_length=10000, verbose_name='定義'),
        ),
    ]
