# Generated by Django 2.1.5 on 2020-04-05 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kukan', '0002_auto_20200405_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='test_source',
        ),
        migrations.AlterField(
            model_name='testresult',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kukan.TestSource', verbose_name='問題元'),
        ),
    ]
