# Generated by Django 2.0.1 on 2018-03-03 00:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kukan', '0003_auto_20180228_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kanji',
            name='update_time',
        ),
        migrations.AddField(
            model_name='example',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='変更日付'),
            preserve_default=False,
        ),
    ]
