# Generated by Django 2.0.1 on 2018-03-03 01:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kukan', '0004_auto_20180303_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='作成日付'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='example',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='変更日付'),
        ),
    ]
