# Generated by Django 2.0.1 on 2018-03-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kukan', '0006_classification_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kanken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kyu', models.CharField(max_length=3, verbose_name='漢字検定')),
                ('difficulty', models.IntegerField()),
            ],
            options={
                'ordering': ['difficulty'],
            },
        ),
        migrations.RemoveField(
            model_name='classification',
            name='difficulty',
        ),
    ]
