# Generated by Django 2.0.1 on 2018-03-03 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kukan', '0007_auto_20180303_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanji',
            name='kanken',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kukan.Kanken', verbose_name='漢検'),
            preserve_default=False,
        ),
    ]
