# Generated by Django 2.0.1 on 2018-03-03 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kukan', '0008_kanji_kanken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kanji',
            name='kanken_kyu',
        ),
    ]
