# Generated by Django 2.0.1 on 2018-03-03 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kukan', '0010_example_kanken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='example',
            old_name='update_time',
            new_name='updated_time',
        ),
    ]
