# Generated by Django 2.0.1 on 2018-03-04 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kukan', '0011_auto_20180303_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kanji',
            name='anki_Classification',
        ),
        migrations.RemoveField(
            model_name='kanji',
            name='anki_Components',
        ),
        migrations.RemoveField(
            model_name='kanji',
            name='anki_Frequency',
        ),
        migrations.RemoveField(
            model_name='kanji',
            name='anki_JLPT_Level',
        ),
        migrations.RemoveField(
            model_name='kanji',
            name='anki_Jouyou_Grade',
        ),
        migrations.RemoveField(
            model_name='kanji',
            name='anki_Keyword',
        ),
        migrations.RemoveField(
            model_name='kanji',
            name='anki_Kunyomi',
        ),
        migrations.RemoveField(
            model_name='kanji',
            name='anki_Nanori',
        ),
        migrations.RemoveField(
            model_name='kanji',
            name='anki_Number_of_Strokes',
        ),
        migrations.RemoveField(
            model_name='kanji',
            name='anki_Onyomi',
        ),
        migrations.RemoveField(
            model_name='kanji',
            name='anki_Radical_Number',
        ),
        migrations.RemoveField(
            model_name='kanji',
            name='anki_Radical_Reading',
        ),
        migrations.RemoveField(
            model_name='kanji',
            name='anki_Radical_Strokes',
        ),
    ]
