# Generated by Django 2.0.1 on 2018-03-04 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kukan', '0012_auto_20180304_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kanji',
            name='anki_kjBunrui',
        ),
        migrations.RemoveField(
            model_name='kanji',
            name='anki_kjKanjiKentei',
        ),
    ]
