# Generated by Django 2.0.1 on 2018-03-04 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kukan', '0013_auto_20180304_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kanji',
            name='anki_Kanji',
        ),
    ]
