# Generated by Django 2.0.1 on 2018-03-04 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kukan', '0014_remove_kanji_anki_kanji'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kanji',
            name='jukuji',
        ),
    ]
