# Generated by Django 2.0.1 on 2018-03-10 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kukan', '0015_remove_kanji_jukuji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='word',
            field=models.CharField(max_length=10, verbose_name='例'),
        ),
    ]
