# Generated by Django 2.0.1 on 2018-03-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kukan', '0016_auto_20180310_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='exmap',
            name='is_ateji',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
