# Generated by Django 2.0.1 on 2018-03-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kukan', '0017_exmap_is_ateji'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='word_native',
            field=models.CharField(default='', max_length=20, verbose_name='例'),
            preserve_default=False,
        ),
    ]
