# Generated by Django 2.0.1 on 2018-03-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kukan', '0018_example_word_native'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='yomi_native',
            field=models.CharField(blank=True, max_length=30, verbose_name='読み方'),
        ),
        migrations.AlterField(
            model_name='example',
            name='word',
            field=models.CharField(max_length=20, verbose_name='単語－表示'),
        ),
        migrations.AlterField(
            model_name='example',
            name='word_native',
            field=models.CharField(blank=True, max_length=10, verbose_name='単語'),
        ),
        migrations.AlterField(
            model_name='example',
            name='yomi',
            field=models.CharField(blank=True, max_length=30, verbose_name='読み方－表示'),
        ),
    ]
