# Generated by Django 2.0.1 on 2018-03-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kukan', '0019_auto_20180310_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanji',
            name='meaning',
            field=models.CharField(default='', max_length=1000, verbose_name='意味'),
            preserve_default=False,
        ),
    ]
