# Generated by Django 2.0.1 on 2018-03-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kukan', '0020_kanji_meaning'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanji',
            name='external_ref',
            field=models.CharField(blank=True, max_length=1000, verbose_name='外部辞典'),
        ),
        migrations.AlterField(
            model_name='kanji',
            name='meaning',
            field=models.CharField(blank=True, max_length=1000, verbose_name='意味'),
        ),
    ]
