# Generated by Django 2.0.1 on 2018-03-14 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kukan', '0021_auto_20180313_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kanji',
            name='anki_kjBushu',
        ),
    ]
