# Generated by Django 2.0.1 on 2018-03-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kukan', '0022_remove_kanji_anki_kjbushu'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='reading_simple',
            field=models.CharField(default='', max_length=20, verbose_name='読み'),
            preserve_default=False,
        ),
    ]
