# Generated by Django 2.0.1 on 2018-04-01 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kukan', '0023_reading_reading_simple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='is_joyo',
            field=models.BooleanField(verbose_name='常表例'),
        ),
        migrations.AlterField(
            model_name='example',
            name='word',
            field=models.CharField(max_length=20, verbose_name='単語'),
        ),
        migrations.AlterField(
            model_name='example',
            name='word_native',
            field=models.CharField(blank=True, max_length=10, verbose_name='単語-例文'),
        ),
        migrations.AlterField(
            model_name='example',
            name='yomi',
            field=models.CharField(blank=True, max_length=30, verbose_name='読み方'),
        ),
        migrations.AlterField(
            model_name='example',
            name='yomi_native',
            field=models.CharField(blank=True, max_length=30, verbose_name='読み方-例文'),
        ),
        migrations.AlterField(
            model_name='kanji',
            name='classification',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='kukan.Classification', verbose_name='種別'),
        ),
    ]
