# Generated by Django 2.0.1 on 2018-04-01 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kukan', '0024_auto_20180401_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanji',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kukan.Classification', verbose_name='種別'),
        ),
    ]
