# Generated by Django 2.0.1 on 2018-04-02 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kukan', '0025_auto_20180401_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='KoukiBushu',
            fields=[
                ('bushu', models.CharField(max_length=1, primary_key=True, serialize=False, verbose_name='BUSHU')),
                ('variations', models.CharField(max_length=5, verbose_name='VARIATIONS')),
                ('reading', models.CharField(max_length=50, verbose_name='READING')),
                ('number', models.IntegerField()),
            ],
        ),
    ]
