# Generated by Django 2.0.1 on 2018-04-02 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kukan', '0026_koukibushu'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanji',
            name='kouki_bushu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kukan.KoukiBushu', verbose_name='部首'),
        ),
        migrations.AlterField(
            model_name='kanji',
            name='bushu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kukan.Bushu', verbose_name='部首'),
        ),
    ]
