# Generated by Django 2.0.1 on 2018-04-02 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kukan', '0027_auto_20180402_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanji',
            name='new_kanji',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kyuji', to='kukan.Kanji'),
        ),
    ]
