# Generated by Django 2.0.1 on 2018-04-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kukan', '0028_kanji_new_kanji'),
    ]

    operations = [
        migrations.CreateModel(
            name='JisClass',
            fields=[
                ('level', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='JIS水準')),
            ],
        ),
    ]
