# Generated by Django 2.0.1 on 2018-04-02 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kukan', '0029_jisclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanji',
            name='jis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kukan.JisClass', verbose_name='JIS水準'),
        ),
    ]
