# Generated by Django 2.0.1 on 2018-04-04 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kukan', '0030_kanji_jis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bunrui',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bunrui', models.CharField(max_length=50, verbose_name='分類')),
            ],
        ),
        migrations.CreateModel(
            name='Yoji',
            fields=[
                ('yoji', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='四字熟語')),
                ('reading', models.CharField(max_length=100, verbose_name='読み方')),
                ('bunrui', models.ManyToManyField(to='kukan.Bunrui')),
                ('kanken', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kukan.Kanken', verbose_name='漢検')),
            ],
        ),
    ]
