# Generated by Django 2.0.1 on 2018-04-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kukan', '0031_bunrui_yoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='yoji',
            name='meaning',
            field=models.CharField(blank=True, max_length=10000, verbose_name='意味'),
        ),
    ]
