# Generated by Django 2.0.1 on 2018-04-04 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kukan', '0032_yoji_meaning'),
    ]

    operations = [
        migrations.AddField(
            model_name='yoji',
            name='has_jitenon_kyu',
            field=models.BooleanField(default=False, verbose_name='級記郵務'),
            preserve_default=False,
        ),
    ]
