# Generated by Django 2.0.1 on 2018-04-07 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kukan', '0033_yoji_has_jitenon_kyu'),
    ]

    operations = [
        migrations.AddField(
            model_name='yoji',
            name='in_anki',
            field=models.BooleanField(default=False, verbose_name='Anki'),
        ),
        migrations.AlterField(
            model_name='yoji',
            name='has_jitenon_kyu',
            field=models.BooleanField(default=False, verbose_name='級記郵務'),
        ),
    ]
