# Generated by Django 2.0.1 on 2018-04-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kukan', '0034_auto_20180407_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='yoji',
            name='anki_cloze',
            field=models.CharField(blank=True, max_length=4, verbose_name='Cloze sequence'),
        ),
    ]
