# Generated by Django 2.0.1 on 2018-04-08 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kukan', '0035_yoji_anki_cloze'),
    ]

    operations = [
        migrations.AddField(
            model_name='yoji',
            name='external_ref',
            field=models.CharField(blank=True, max_length=1000, verbose_name='外部辞典'),
        ),
    ]
