# Generated by Django 2.0.1 on 2018-05-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kukan', '0036_yoji_external_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='koukibushu',
            name='kakusu',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
