# Generated by Django 2.0.1 on 2018-05-06 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kukan', '0037_koukibushu_kakusu'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanjiDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField(blank=True, max_length=1000, verbose_name='意味')),
                ('external_ref', models.CharField(blank=True, max_length=1000, verbose_name='外部辞典')),
                ('anki_English', models.CharField(max_length=1000)),
                ('anki_Examples', models.CharField(max_length=1000)),
                ('anki_Kanji_Radical', models.CharField(max_length=10)),
                ('anki_Traditional_Form', models.CharField(max_length=10)),
                ('anki_Traditional_Radical', models.CharField(max_length=10)),
                ('anki_Reading_Table', models.CharField(max_length=10000)),
                ('anki_kjBushuMei', models.CharField(max_length=100)),
                ('anki_kjIjiDoukun', models.CharField(max_length=5000)),
            ],
        ),
        migrations.AlterModelOptions(
            name='kanji',
            options={},
        ),
        migrations.AlterField(
            model_name='kanji',
            name='new_kanji',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kyuji2', to='kukan.Kanji'),
        ),
        migrations.AddField(
            model_name='kanjidetails',
            name='kanji',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kukan.Kanji', verbose_name='漢字'),
        ),
        migrations.AddField(
            model_name='kanjidetails',
            name='new_kanji',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kyuji', to='kukan.Kanji'),
        ),
    ]
