# Generated by Django 2.0.1 on 2018-05-06 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kukan', '0038_auto_20180506_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kanji',
            name='anki_English',
        ),
        migrations.RemoveField(
            model_name='kanji',
            name='anki_Examples',
        ),
        migrations.RemoveField(
            model_name='kanji',
            name='anki_Kanji_Radical',
        ),
        migrations.RemoveField(
            model_name='kanji',
            name='anki_Reading_Table',
        ),
        migrations.RemoveField(
            model_name='kanji',
            name='anki_Traditional_Form',
        ),
        migrations.RemoveField(
            model_name='kanji',
            name='anki_Traditional_Radical',
        ),
        migrations.RemoveField(
            model_name='kanji',
            name='anki_kjBushuMei',
        ),
        migrations.RemoveField(
            model_name='kanji',
            name='anki_kjIjiDoukun',
        ),
        migrations.RemoveField(
            model_name='kanji',
            name='external_ref',
        ),
        migrations.RemoveField(
            model_name='kanji',
            name='meaning',
        ),
        migrations.RemoveField(
            model_name='kanji',
            name='new_kanji',
        ),
    ]
