# Generated by Django 4.2.7 on 2023-12-27 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Start time')),
                ('end_time', models.DateTimeField(verbose_name='End time')),
                ('start_temp', models.FloatField(verbose_name='Starting temperature')),
                ('max_temp', models.FloatField(verbose_name='Max temperature')),
                ('data_points', models.BinaryField(verbose_name='Data points')),
            ],
        ),
    ]
