# Generated by Django 4.2.7 on 2023-12-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempmon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_id', models.TextField(max_length=12, verbose_name='Title ID')),
                ('name', models.TextField(max_length=2000, verbose_name='Name')),
            ],
        ),
    ]
