# Generated by Django 4.2.7 on 2023-12-31 02:31

from django.db import migrations, models


def add_duration(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    PlaySession = apps.get_model("tempmon", "PlaySession")
    for session in PlaySession.objects.all():
        session.duration = session.end_time - session.start_time
        session.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tempmon', '0003_auto_20231228_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='playsession',
            name='duration',
            field=models.DurationField(verbose_name='Duration', null=True, blank=True),
        ),
        migrations.RunPython(add_duration),
    ]

