# Generated by Django 4.2.7 on 2023-12-31 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempmon', '0004_playsession_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playsession',
            name='duration',
            field=models.DurationField(verbose_name='Duration'),
        ),
    ]
