# Generated by Django 4.2.7 on 2024-01-03 05:11

from django.db import migrations, models


def create_initial_psn_api_key(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    PsnApiKey = apps.get_model("tempmon", "PsnApiKey")
    PsnApiKey.objects.create(code='__dummy__')


class Migration(migrations.Migration):

    dependencies = [
        ('tempmon', '0005_alter_playsession_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsnApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='__dummy__', max_length=100, verbose_name='npsso code')),
            ],
        ),
        migrations.RunPython(create_initial_psn_api_key),
    ]


