# Generated by Django 4.2.7 on 2024-01-07 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tempmon', '0006_psnapikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePerSessionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField(verbose_name='Duration', null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tempmon.psgame')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tempmon.playsession')),
            ],
        ),
    ]
