# Generated by Django 4.2.7 on 2024-01-07 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempmon', '0007_gamepersessioninfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='psgame',
            name='play_time',
            field=models.DurationField(null=True, verbose_name='Play time'),
        ),
    ]
