# Generated by Django 4.2.7 on 2024-04-16 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tempmon', '0009_psgame_last_played'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psgame',
            name='last_played',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last played'),
        ),
    ]
