# Generated by Django 2.0.1 on 2019-01-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementCommandRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd_pid', models.IntegerField(verbose_name='Command PID')),
                ('cmd_name', models.CharField(max_length=20, verbose_name='Command name')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Timestamp')),
            ],
        ),
    ]
