# Generated by Django 2.1.5 on 2021-11-23 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_date', models.DateTimeField(verbose_name='測定日')),
                ('weight', models.FloatField(verbose_name='体重')),
                ('fat_pct', models.FloatField(blank=True, default=None, null=True, verbose_name='体脂肪率')),
                ('muscle_pct', models.FloatField(blank=True, default=None, null=True, verbose_name='骨格筋率')),
            ],
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker', models.CharField(max_length=50, verbose_name='メーカー')),
                ('model', models.CharField(max_length=100, verbose_name='機種')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_scale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wtrack.Scale', verbose_name='基本体重計')),
            ],
        ),
        migrations.AddField(
            model_name='measurement',
            name='scale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wtrack.Scale', verbose_name='部首'),
        ),
    ]
