# Generated by Django 2.1.5 on 2022-01-29 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wtrack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='token',
            field=models.BinaryField(null=True, verbose_name='API Token'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='scale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wtrack.Scale', verbose_name='体重計'),
        ),
    ]
